### ISSUE TITLE
Support dynamic color scheme change

### ISSUE THREAD

**Issue by YtvwlD** [chaosdorf/twenty-seventeen-child#1]
Currently, we evaluate `prefers-color-scheme` only on load. This can be done better.

**Comment by Dorson** [comment]
The CSS rule for **@media screen and (prefers-color-scheme: dark) { }**  would work,
but it would enforce one color only, and for the users that have that rule ON already.
No way to switch it ON, OFF during the sunny moments. Or give it to all as a click-able option. 

To resolve that, I did the hard work.

Made and tested the code for a CSS color switch with memory. Great for the night and evening time.

See live demo on GitHub page:

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Have fun, feel free to fork, copy, adopt, port, etc...

**Comment by YtvwlD** [comment]
Hm, yeah. I'm not sure if putting this into websites is the right way to go. People can already change that in their operating systems - or install add-ons to their browsers if they can't do the former.
(This issue is closed because we conditionally load the CSS on `prefers-color-scheme: dark` which works.)
