### ISSUE TITLE
Font for title doesn't show on other pages than home

### ISSUE THREAD

**Issue by nomaster** [chaosdorf/twenty-seventeen-child#4]
Only home writes the site title in an `h1` element, all others use a `p` element for reasons unknown. Lets say all elements of the class `site-title` get the Computerfont applied.

https://github.com/chaosdorf/twenty-seventeen-child/blob/b4b34f361691974fa02a858944dea6bd7bcca224/style.css#L261

**Comment by YtvwlD** [comment]
Um, okay. I guess that's optimization for search engines - `h1` tends to be the description for the current page.
